name: Test

on:
  pull_request:
    branches:
      - master # Change 'main' to your default branch name if different
  push:
    branches:
      - master # Change 'main' to your default branch name if different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test # Change this command if your test command is different
